services:
  pubsub:
    build:
      context: .
    image: ghcr.io/picosh/pubsub:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./ssh_data:/ssh_data
    ports:
      - 2222:2222
