name: Test and Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Lint the codebase
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: -E goimports -E godot --timeout 10m
    - name: Run tests
      run: |
        go test -v ./... -cover -race -coverprofile=coverage.out
        go tool cover -func=coverage.out -o=coverage.out
